---
integration:
  name: rspec
requires:
  - ice_nine
matcher:
  subjects:
    - IceNine*
  ignore:
    - IceNine::RecursionGuard::ObjectSet#guard
mutation:
  timeout: 1.0
coverage_criteria:
  timeout: true
